using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyToweStatus : MonoBehaviour
{
    [SerializeField] int towerHelat;
    UIManager u覺Healt;
    private void Start()
    {
        u覺Healt = FindObjectOfType<UIManager>();
        u覺Healt.TowerHealtText(towerHelat);
    }
    public void ToverHealtDecrease()
    {
        towerHelat -= 1;
        if (towerHelat < 0)
        {
            GameManager.Instance.GameWin();
            towerHelat = 0;

        }
       
    }
    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag("Kid"))
        {
            ToverHealtDecrease();
            u覺Healt.TowerHealtText(towerHelat);
            Destroy(other.gameObject);
        }
    }
}
